module.exports = {
  'vr-audio': require('./vr-audio'),
  'vr-cube': require('./vr-cube'),
  'vr-curvedPlane1': require('./vr-curvedPlane1'),
  'vr-curvedPlane2': require('./vr-curvedPlane2'),
  'vr-cylinder': require('./vr-cylinder'),
  'vr-element': require('./vr-element'),
  'vr-grid': require('./vr-grid'),
  'vr-hemispherelight': require('./vr-hemispherelight'),
  'vr-image': require('./vr-image'),
  'vr-model': require('./vr-model'),
  'vr-obj-loader': require('./vr-obj-loader'),
  'vr-plane': require('./vr-plane'),
  'vr-skybox': require('./vr-skybox'),
  'vr-skysphere': require('./vr-skysphere'),
  'vr-sphere': require('./vr-sphere'),
  'vr-text': require('./vr-text'),
  'vr-video': require('./vr-video'),
  'vr-video360': require('./vr-video360')
};
